### ISSUE TITLE
repyV2/ directory empty after build.py

### ISSUE THREAD

**Issue by yyzhuang** [SeattleTestbed/nodemanager#108]
When running build.py, the repyV2/ directory doesn't seem to have content copied over. 
`$ cd ../scripts`
`$ python build.py -t`
`Building into /home/yanyan/nodemanager/RUNNABLE`
`Done building!`
`$ cd ../RUNNABLE`
`$ cd repyV2`
`$ ls -l`
`total 0`

As a result, startvessel_ex fails when calling command `/usr/bin/python repyV2/repy.py...` The repyV1/ directory is also empty.

**Comment by aaaaalbert** [comment]
This problem is a result of https://github.com/SeattleTestbed/common/pull/26 (and foregoing PRs) not having been merged yet.

We are in the process of adding functionality so that `config_build.txt` can specify subdirectories under the target build path into which files are then copied.

E.g., to put all of `repy_v2` into the nodemanager's target dir *and* the `repyV2` subdir, `config_build.txt` will state
```
DEPENDENCIES/repy_v2/*
DEPENDENCIES/repy_v2/* repyV2
```

**Comment by aaaaalbert** [comment]
See also #111 and test instructions.

**Comment by aaaaalbert** [comment]
Fixed with merging SeattleTestbed/nodemanager#111 and SeattleTestbed/common#26.
