### ISSUE TITLE
Install from beta Clearinghouse causes many node manager instances

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/nodemanager#73]
I created a customized install from beta Clearinghourse https://betaseattleclearinghouse.poly.edu/custom_install/ I split my local node into two. After install, 
```
ps -ef | grep nmmain | wc -l
      32
```

**Comment by aaaaalbert** [comment]
Since there was no further report on a problem like this since it was originally reported, I'm closing this issue. The Betaseattleclearinghouse will get an update and start shipping a totally new installer pretty soon now, too. (This new installer has seen quite a bit of testing thanks to @SensibilityTestbed, and the problem didn't appear there.)
